### PR TITLE
Resolve 96: Make all F/A-18C / F-14B presets consistent

### PR DESCRIPTION
**Pull request by martinco**

### CODE REVIEW

**Comment by 132nd-etcher** [comment]
👍

**Comment by 132nd-etcher** [comment]
@martinco there is something weird with this PR.

I was a lot of deletions and went through the diff.

Do you know why all the `modulation` tables got scrubbed?

For example:

```
                                                ["modulations"] =
                                                {
                                                    [1] = 0,
                                                    [2] = 0,
                                                    [3] = 0,
                                                    [4] = 0,
                                                    [5] = 0,
                                                    [6] = 0,
                                                    [7] = 0,
                                                    [8] = 0,
                                                    [9] = 0,
                                                    [10] = 0,
                                                    [11] = 0,
                                                    [12] = 0,
                                                    [13] = 0,
                                                    [14] = 0,
                                                    [15] = 0,
                                                    [16] = 0,
                                                    [17] = 0,
                                                    [18] = 0,
                                                    [19] = 0,
                                                    [20] = 0,
                                                }, -- end of ["modulations"]```

**Comment by martinco** [comment]
Because they're optional, and the F18 i picked the template from from didn't have that table in the mission file:

See: Line 163859 of the current master for an example with no modulations

I believe the editor only puts them in if one gets flipped off and on at some point

If i put the empty modulations table in instead of this, then you'll get: 618 insertions(+), 342 deletions(-) with several 18s getting the modulations where they didn't before

**Comment by 132nd-etcher** [comment]
That makes perfect sense. Thanks for clearing it up!

**Comment by 132nd-etcher** [comment]
👍

**Pull request merged**
